/**
 * GET /api/chat/download?ref=<csvRef>
 *
 * Serves a stored binary artifact (today: CSVs generated by the agent's
 * generateCsv tool). Auth-gated to a valid Firebase ID token so that
 * csvRef IDs aren't guessable download URLs — the store is process-local
 * and ephemeral, but leaking an ID still shouldn't let an unauthenticated
 * caller pull a user's data.
 *
 * The store is backed by lib/tools/flyer-store.ts which holds entries for
 * 30 minutes; after that a 404 is returned and the agent would need to
 * re-run generateCsv.
 */

import { type NextRequest, NextResponse } from "next/server";
import { getArtifact } from "@/lib/tools/flyer-store";
import { verifyIdToken } from "@/lib/firestore-admin";

export const runtime = "nodejs";

export async function GET(req: NextRequest) {
  // Auth: require a valid Firebase token. We don't need to cross-check
  // email here — the store is process-local, not per-user, and any
  // signed-in GMCC user can download any ref that was generated in the
  // same warm function instance.
  const idToken = req.headers.get("Authorization")?.replace("Bearer ", "") ?? "";
  if (!idToken) {
    return NextResponse.json({ error: "Authentication required" }, { status: 401 });
  }
  const uid = await verifyIdToken(idToken);
  if (!uid) {
    return NextResponse.json({ error: "Invalid token" }, { status: 401 });
  }

  const ref = req.nextUrl.searchParams.get("ref");
  if (!ref) {
    return NextResponse.json({ error: "ref is required" }, { status: 400 });
  }

  const entry = await getArtifact(ref);
  if (!entry) {
    return NextResponse.json(
      { error: "Artifact not found or expired. Ask the agent to regenerate it." },
      { status: 404 },
    );
  }

  const bytes = Buffer.from(entry.base64, "base64");
  const contentType =
    entry.kind === "csv" ? "text/csv; charset=utf-8" : "application/pdf";
  const filename = entry.filename ?? `gmcc-${entry.kind}-${ref}.${entry.kind}`;

  return new Response(bytes, {
    headers: {
      "Content-Type": contentType,
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "private, no-store",
    },
  });
}
