"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useAuth } from "@/contexts/AuthContext";
import LoadingSpinner from "@/components/LoadingSpinner";
import { emailRequest } from "@/lib/msal-config";
import { getSignatureHtml, hasSignature, buildHtmlBodyWithSignature } from "@/lib/signature-store";
import SignatureFixModal from "@/components/SignatureFixModal";
import { trackEvent } from "@/lib/posthog";
import FollowUpToggle from "@/components/FollowUpToggle";
import AgentIntelCard from "./AgentIntelCard";
import type { RealtorInfo } from "./FlierButton";

type RecipientTab = "realtor" | "borrower" | "myself";

interface ProgramEntry {
  name: string;
  product_id?: string;
}

interface MultiEmailModalProps {
  programs: ProgramEntry[];
  summary: string;
  propertyAddress?: string;
  listingPrice?: number;
  realtorInfo: RealtorInfo;
  /** Pre-fetched research text from the summary modal */
  preResearch?: string | null;
  onClose: () => void;
  /** Go back to the summary modal */
  onBackToSummary?: () => void;
  /** Fetch a PDF for a given productId. Returns null if unavailable. */
  fetchPdf: (productId: string) => Promise<Blob | null>;
}

function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    blob.arrayBuffer().then((buf) => {
      const bytes = new Uint8Array(buf);
      let binary = "";
      const CHUNK = 8192;
      for (let i = 0; i < bytes.length; i += CHUNK) {
        binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
      }
      resolve(btoa(binary));
    }).catch(reject);
  });
}

/** Build a nicely formatted HTML document from the markdown summary. */
function buildSummaryHtml(
  markdown: string,
  programs: ProgramEntry[],
  address?: string,
  price?: number,
): string {
  // Convert markdown to simple HTML
  let html = markdown
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^### (.+)$/gm, '<h3 style="margin:16px 0 6px;font-size:14px;color:#374151">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="margin:20px 0 8px;font-size:16px;color:#1f2937">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="margin:24px 0 10px;font-size:18px;color:#111827">$1</h1>')
    .replace(/^---$/gm, '<hr style="border:none;border-top:1px solid #e5e7eb;margin:16px 0">')
    .replace(/^\d+\.\s+(.+)$/gm, '<li style="margin:2px 0">$1</li>')
    .replace(/^[-*]\s+(.+)$/gm, '<li style="margin:2px 0">$1</li>')
    .replace(/\n/g, "<br>");

  // Wrap consecutive <li> in <ul>
  html = html.replace(/(<li[^>]*>.*?<\/li><br>?)+/g, (match) =>
    '<ul style="margin:8px 0;padding-left:20px">' + match.replace(/<br>/g, "") + "</ul>",
  );

  const priceStr = price ? `$${price.toLocaleString()}` : "";
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Program Summary</title></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:640px;margin:0 auto;padding:24px;color:#374151;line-height:1.6">
<div style="border-bottom:2px solid #dc2626;padding-bottom:12px;margin-bottom:20px">
<h1 style="margin:0;font-size:20px;color:#dc2626">GMCC Multi-Program Summary</h1>
${address ? `<p style="margin:4px 0 0;color:#6b7280;font-size:13px">${address}${priceStr ? ` — ${priceStr}` : ""}</p>` : ""}
<p style="margin:4px 0 0;color:#6b7280;font-size:13px">Programs: ${programs.map((p) => p.name).join(", ")}</p>
</div>
${html}
<div style="margin-top:24px;padding-top:12px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:11px">
Generated by GMCC Program Matching Tool
</div>
</body></html>`;
}

export default function MultiEmailModal({
  programs,
  summary,
  propertyAddress,
  listingPrice,
  realtorInfo,
  preResearch,
  onClose,
  onBackToSummary,
  fetchPdf,
}: MultiEmailModalProps) {
  const { user, signIn, getMsalAccessToken, getIdToken } = useAuth();

  const [tab, setTab] = useState<RecipientTab>("realtor");
  const [toEmail, setToEmail] = useState("");
  const [toName, setToName] = useState("");
  const [ccEmail, setCcEmail] = useState("");
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [aiPrompt, setAiPrompt] = useState("");
  const [aiLoading, setAiLoading] = useState(false);
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [sendProgress, setSendProgress] = useState("");
  const [aiSearched, setAiSearched] = useState(false);
  const [attachSummary, setAttachSummary] = useState(false);
  const [sentWithSig, setSentWithSig] = useState(false);
  const [followUpEnabled, setFollowUpEnabled] = useState(false);
  const [followUpDays, setFollowUpDays] = useState(3);
  const [followUpMode, setFollowUpMode] = useState<"remind" | "auto-send">("remind");
  const [agentResearch, setAgentResearch] = useState<string | null>(preResearch ?? null);
  const [sigFixOpen, setSigFixOpen] = useState(false);
  const [sigOk, setSigOk] = useState(() => hasSignature());
  const autoGenTriggered = useRef(false);

  const loName = user?.displayName || user?.email || "Loan Officer";
  const programsWithFlyer = programs.filter((p) => p.product_id);

  const realtorEmail = realtorInfo.email;
  const realtorName = realtorInfo.name;
  useEffect(() => {
    setError(null);
    setSent(false);
    setCcEmail("");
    setAiPrompt("");
    if (tab === "myself") {
      setToEmail(user?.email ?? "");
      setToName(loName);
      setSubject(`Program Flyers: ${programs.map((p) => p.name).join(", ")}`);
      const price = listingPrice ? `$${listingPrice.toLocaleString()}` : "N/A";
      setBody(
        [
          `Saving these program flyers for my records.`,
          "",
          `Property: ${propertyAddress || "N/A"}`,
          `Listing Price: ${price}`,
          `Programs: ${programs.map((p) => p.name).join(", ")}`,
          "",
          `${programsWithFlyer.length} flyer(s) attached.`,
        ].join("\n"),
      );
    } else if (tab === "realtor") {
      setToEmail(realtorEmail);
      setToName(realtorName);
      setSubject("");
      setBody("");
    } else {
      setToEmail("");
      setToName("");
      setSubject("");
      setBody("");
    }
  }, [tab, user, realtorEmail, realtorName]); // eslint-disable-line react-hooks/exhaustive-deps

  const generateEmail = useCallback(async (prompt: string, researchOverride?: string | null) => {
    setAiLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/suggest-multi-email", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          recipientType: tab,
          userPrompt: prompt,
          programs: programs.map((p) => p.name),
          summary,
          propertyAddress,
          listingPrice: listingPrice ? String(listingPrice) : undefined,
          realtorName: realtorInfo.name,
          realtorEmail: realtorInfo.email,
          realtorCompany: realtorInfo.company,
          loName,
          hasSignature: hasSignature(),
          realtorResearch: researchOverride !== undefined ? researchOverride : agentResearch,
        }),
      });
      const data = (await res.json()) as {
        subject?: string;
        body?: string;
        error?: string;
        searched?: boolean;
      };
      if (!res.ok || data.error) {
        setError(data.error ?? "AI suggestion failed.");
        return;
      }
      if (data.subject) setSubject(data.subject);
      if (data.body) setBody(data.body);
      setAiSearched(!!data.searched);
    } catch {
      setError("AI suggestion failed. Please try again.");
    } finally {
      setAiLoading(false);
    }
  }, [tab, programs, summary, propertyAddress, listingPrice, realtorInfo, loName, agentResearch]);

  async function handleAiSuggest() {
    if (!aiPrompt.trim()) return;
    await generateEmail(aiPrompt);
  }

  const handleResearchComplete = useCallback((research: import("@/lib/redis-cache").AgentResearch | null) => {
    if (research) {
      const text = [
        research.summary,
        research.specialties.length > 0 ? `Specialties: ${research.specialties.join(", ")}` : "",
        (typeof research.reviews === "string" ? research.reviews : "") || "",
        research.personalHooks.length > 0 ? `Hooks: ${research.personalHooks.join("; ")}` : "",
      ].filter(Boolean).join("\n");
      setAgentResearch(text);

      // Auto-generate only if no preResearch (preResearch triggers via the effect below)
      if (!preResearch && tab === "realtor" && !autoGenTriggered.current) {
        autoGenTriggered.current = true;
        generateEmail(
          "Write a personalized outreach email introducing these loan programs. Use the research to personalize.",
          text,
        );
      }
    }
  }, [tab, generateEmail, preResearch]);

  // Auto-generate on mount when preResearch is available (from summary modal)
  useEffect(() => {
    if (preResearch && tab === "realtor" && !autoGenTriggered.current && !subject && !body) {
      autoGenTriggered.current = true;
      generateEmail(
        "Write a personalized outreach email introducing these loan programs. Use the research to personalize.",
        preResearch,
      );
    }
  }, [preResearch, tab, subject, body, generateEmail]);

  async function handleSend() {
    if (sending) return;
    if (!hasSignature()) { setSigFixOpen(true); return; }
    if (!toEmail.trim()) { setError("Recipient email is required."); return; }
    if (!subject.trim()) { setError("Subject is required."); return; }

    setError(null);
    setSending(true);

    try {
      if (!user) await signIn();

      setSendProgress("Getting email permission...");
      const msalToken = await getMsalAccessToken(emailRequest.scopes);
      if (!msalToken) {
        setError("Could not get email permission. Please sign in again.");
        return;
      }

      // Fetch all flyer PDFs in parallel
      const attachments: { name: string; base64: string }[] = [];
      if (programsWithFlyer.length > 0) {
        setSendProgress(`Generating ${programsWithFlyer.length} flyer(s)...`);
        const pdfResults = await Promise.all(
          programsWithFlyer.map(async (p) => {
            const blob = await fetchPdf(p.product_id!);
            if (!blob) return null;
            const base64 = await blobToBase64(blob);
            return { name: `${p.product_id}-flyer.pdf`, base64 };
          }),
        );
        for (const r of pdfResults) {
          if (r) attachments.push(r);
        }
      }

      setSendProgress("Sending email...");

      // Build email body — append signature if the user has one saved
      const sig = getSignatureHtml();
      const useHtml = !!sig;
      setSentWithSig(useHtml);
      const emailBody = useHtml
        ? { contentType: "HTML" as const, content: buildHtmlBodyWithSignature(body, sig) }
        : { contentType: "Text" as const, content: body };

      const message: Record<string, unknown> = {
        subject,
        body: emailBody,
        toRecipients: [
          { emailAddress: { address: toEmail.trim(), name: toName.trim() || undefined } },
        ],
        ...(ccEmail.trim()
          ? { ccRecipients: [{ emailAddress: { address: ccEmail.trim() } }] }
          : {}),
        attachments: [
          ...attachments.map((a) => ({
            "@odata.type": "#microsoft.graph.fileAttachment",
            name: a.name,
            contentType: "application/pdf",
            contentBytes: a.base64,
          })),
          // Attach formatted summary as HTML file if toggled on
          ...(attachSummary && summary
            ? [{
                "@odata.type": "#microsoft.graph.fileAttachment",
                name: "program-summary.html",
                contentType: "text/html",
                contentBytes: btoa(unescape(encodeURIComponent(buildSummaryHtml(summary, programs, propertyAddress, listingPrice)))),
              }]
            : []),
        ],
      };

      const res = await fetch("https://graph.microsoft.com/v1.0/me/sendMail", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${msalToken}`,
        },
        body: JSON.stringify({ message, saveToSentItems: true }),
      });

      if (!res.ok) {
        const errData = (await res.json().catch(() => ({}))) as {
          error?: { message?: string };
        };
        setError(errData.error?.message ?? "Failed to send email.");
        return;
      }

      setSent(true);
      trackEvent("email_sent", { recipientType: tab, programs: programs.map(p => p.name), property: propertyAddress, programCount: programs.length });

      // Record all sent emails (fire and forget)
      if (tab !== "myself") {
        const idToken = await getIdToken().catch(() => null);
        if (idToken) {
          fetch("/api/follow-up/record", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${idToken}`,
            },
            body: JSON.stringify({
              recipientEmail: toEmail.trim(),
              recipientName: toName.trim(),
              recipientType: tab,
              subject,
              body,
              propertyAddress,
              programNames: programs.map((p) => p.name),
              followUpDays: followUpEnabled ? followUpDays : null,
              followUpMode: followUpEnabled ? followUpMode : null,
              userEmail: user?.email,
            }),
          }).catch(() => console.warn("[email-record] Recording failed (non-critical)"));
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to send email.");
    } finally {
      setSending(false);
      setSendProgress("");
    }
  }

  const tabs: { id: RecipientTab; label: string }[] = [
    { id: "realtor", label: "Send to Realtor" },
    { id: "borrower", label: "Send to Borrower" },
    { id: "myself", label: "Send to Myself" },
  ];

  const showNameField = tab !== "myself";

  return (
    <div
      className="fixed inset-0 z-[70] flex items-center justify-center bg-black/70 p-4"
      onClick={onClose}
    >
      <div
        className="relative flex w-full max-w-lg flex-col overflow-hidden rounded-xl bg-white shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-gray-200 px-5 py-3.5">
          <div className="flex items-center gap-3">
            {onBackToSummary && (
              <button
                onClick={onBackToSummary}
                className="inline-flex items-center gap-1 text-xs font-medium text-gray-500 hover:text-gray-700"
                title="Back to summary"
              >
                <svg width="12" height="12" viewBox="0 0 16 16" fill="none">
                  <path d="M10 4L6 8l4 4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
                Summary
              </button>
            )}
            <div>
              <span className="text-sm font-semibold text-gray-800">
                Email {programs.length} Programs
              </span>
              <span className="ml-2 text-xs text-gray-400">
                {programsWithFlyer.length} flyer(s) attached
              </span>
            </div>
          </div>
          <button
            onClick={onClose}
            className="flex h-7 w-7 items-center justify-center rounded-full bg-gray-100 text-gray-500 hover:bg-gray-200"
          >
            <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
              <path d="M12 4L4 12M4 4l8 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
            </svg>
          </button>
        </div>

        <div className="max-h-[80vh] overflow-y-auto">
          {/* Tabs */}
          <div className="flex border-b border-gray-100 px-5 pt-3">
            {tabs.map(({ id, label }) => (
              <button
                key={id}
                onClick={() => setTab(id)}
                className={`mr-4 border-b-2 pb-2 text-xs font-medium transition-colors ${
                  tab === id
                    ? "border-red-600 text-red-600"
                    : "border-transparent text-gray-500 hover:text-gray-700"
                }`}
              >
                {label}
              </button>
            ))}
          </div>

          <div className="space-y-3 p-5">
            {sent ? (
              <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-center">
                <div className="text-2xl mb-1">✓</div>
                <p className="text-sm font-medium text-emerald-800">Email sent successfully!</p>
                <p className="text-xs text-emerald-600 mt-0.5">
                  Sent to {toEmail} with {programsWithFlyer.length} flyer(s) attached.
                  {ccEmail.trim() ? ` CC: ${ccEmail.trim()}` : ""}
                  {sentWithSig ? " — with your signature." : ""}
                </p>
                <button
                  onClick={onClose}
                  className="mt-3 rounded-md bg-emerald-600 px-4 py-1.5 text-xs font-medium text-white hover:bg-emerald-700"
                >
                  Close
                </button>
              </div>
            ) : (
              <>
                {/* Recipient fields */}
                <div className="space-y-2">
                  {showNameField && (
                    <div>
                      <label className="mb-0.5 block text-[0.7rem] font-medium uppercase tracking-wide text-gray-500">
                        Recipient Name
                      </label>
                      <input
                        type="text"
                        value={toName}
                        onChange={(e) => setToName(e.target.value)}
                        placeholder={tab === "realtor" ? "Realtor name" : "Borrower name"}
                        className="w-full rounded-md border border-gray-200 px-3 py-1.5 text-sm text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-400"
                      />
                    </div>
                  )}
                  <div>
                    <label className="mb-0.5 block text-[0.7rem] font-medium uppercase tracking-wide text-gray-500">
                      To Email
                    </label>
                    <input
                      type="email"
                      value={toEmail}
                      onChange={(e) => setToEmail(e.target.value)}
                      readOnly={tab === "myself"}
                      placeholder="recipient@example.com"
                      className={`w-full rounded-md border border-gray-200 px-3 py-1.5 text-sm text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-400 ${
                        tab === "myself" ? "bg-gray-50 text-gray-500" : ""
                      }`}
                    />
                  </div>
                  {tab !== "myself" && (
                    <div>
                      <label className="mb-0.5 block text-[0.7rem] font-medium uppercase tracking-wide text-gray-500">
                        CC <span className="normal-case font-normal text-gray-400">(optional)</span>
                      </label>
                      <input
                        type="email"
                        value={ccEmail}
                        onChange={(e) => setCcEmail(e.target.value)}
                        placeholder="cc@example.com"
                        className="w-full rounded-md border border-gray-200 px-3 py-1.5 text-sm text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-400"
                      />
                    </div>
                  )}

                  {/* Agent Intel — skip if preResearch already provided from summary modal */}
                  {!preResearch && tab === "realtor" && (realtorInfo.name || realtorInfo.email || realtorInfo.company) && (
                    <AgentIntelCard
                      realtorName={realtorInfo.name}
                      realtorEmail={realtorInfo.email}
                      realtorCompany={realtorInfo.company}
                      onResearchComplete={handleResearchComplete}
                    />
                  )}
                  {preResearch && tab === "realtor" && (
                    <div className="rounded-lg border border-indigo-100 bg-indigo-50/40 px-3 py-2 flex items-center gap-2">
                      <svg width="14" height="14" viewBox="0 0 16 16" fill="none" className="text-indigo-500">
                        <circle cx="8" cy="5" r="3" stroke="currentColor" strokeWidth="1.3" />
                        <path d="M2 14c0-3.3 2.7-6 6-6s6 2.7 6 6" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" />
                      </svg>
                      <span className="text-xs text-indigo-600">Agent research from summary used for personalization</span>
                    </div>
                  )}

                  <div>
                    <label className="mb-0.5 block text-[0.7rem] font-medium uppercase tracking-wide text-gray-500">
                      Subject
                    </label>
                    <input
                      type="text"
                      value={subject}
                      onChange={(e) => setSubject(e.target.value)}
                      placeholder="Email subject"
                      className="w-full rounded-md border border-gray-200 px-3 py-1.5 text-sm text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-400"
                    />
                  </div>
                  <div>
                    <label className="mb-0.5 block text-[0.7rem] font-medium uppercase tracking-wide text-gray-500">
                      Body
                    </label>
                    <textarea
                      value={body}
                      onChange={(e) => setBody(e.target.value)}
                      rows={7}
                      placeholder="Email body..."
                      className="w-full rounded-md border border-gray-200 px-3 py-1.5 text-sm text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-400 resize-y"
                    />
                  </div>
                </div>

                {/* AI Assist — not shown for "myself" */}
                {tab !== "myself" && (
                  <div className="rounded-lg border border-violet-200 bg-violet-50 p-3 space-y-2">
                    <p className="text-[0.7rem] font-semibold uppercase tracking-wide text-violet-700">
                      AI Assist — Gemini
                    </p>
                    <p className="text-xs text-violet-600">
                      Describe how you'd like the email written. Mention &quot;research the realtor&quot; for AI to personalize using web search.
                    </p>
                    <div className="flex gap-2">
                      <textarea
                        value={aiPrompt}
                        onChange={(e) => { setAiPrompt(e.target.value); e.target.style.height = "auto"; e.target.style.height = e.target.scrollHeight + "px"; }}
                        onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); handleAiSuggest(); } }}
                        placeholder={
                          tab === "realtor"
                            ? 'e.g. "Research the realtor and write a personalized pitch"'
                            : 'e.g. "Friendly intro, highlight program benefits"'
                        }
                        rows={1}
                        className="flex-1 resize-none rounded-md border border-violet-200 bg-white px-2.5 py-1.5 text-xs text-gray-700 placeholder-gray-400 focus:outline-none focus:ring-1 focus:ring-violet-400"
                      />
                      <button
                        onClick={handleAiSuggest}
                        disabled={aiLoading || !aiPrompt.trim()}
                        className="inline-flex items-center gap-1 rounded-md bg-violet-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-violet-700 disabled:opacity-40"
                      >
                        {aiLoading ? <LoadingSpinner size="sm" /> : null}
                        {aiLoading ? "Generating..." : "Generate"}
                      </button>
                    </div>
                    {(subject || body) && !aiLoading && (
                      <div className="space-y-1">
                        <p className="text-[0.65rem] text-violet-500">
                          Subject and body updated above — edit freely before sending.
                        </p>
                        {aiSearched && (
                          <p className="inline-flex items-center gap-1 text-[0.65rem] font-medium text-emerald-600">
                            <svg width="10" height="10" viewBox="0 0 16 16" fill="none">
                              <circle cx="7" cy="7" r="5.5" stroke="currentColor" strokeWidth="1.5" />
                              <path d="M11 11l3.5 3.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                            </svg>
                            AI researched the realtor to personalize this email
                          </p>
                        )}
                      </div>
                    )}
                  </div>
                )}

                {/* Attach summary toggle — "myself" tab only, when summary exists */}
                {tab === "myself" && summary && (
                  <label className="flex items-center gap-2.5 rounded-md border border-violet-200 bg-violet-50 px-3 py-2.5 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={attachSummary}
                      onChange={(e) => setAttachSummary(e.target.checked)}
                      className="h-4 w-4 rounded border-violet-300 text-violet-600 focus:ring-violet-500"
                    />
                    <div>
                      <span className="text-xs font-medium text-violet-800">
                        Attach AI Summary
                      </span>
                      <p className="text-[0.65rem] text-violet-600">
                        Include the multi-program summary as an HTML file
                      </p>
                    </div>
                  </label>
                )}

                {/* Attachments indicator */}
                <div className="rounded-md border border-gray-100 bg-gray-50 px-3 py-2 text-xs text-gray-500 space-y-1">
                  <div className="flex items-center gap-2">
                    <svg width="13" height="13" viewBox="0 0 16 16" fill="none">
                      <path d="M3 2h10v12H3V2z" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" />
                      <path d="M5 6h6M5 9h6M5 12h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                    </svg>
                    <span>{programsWithFlyer.length} flyer PDF(s) will be attached:</span>
                  </div>
                  <div className="flex flex-wrap gap-1 pl-5">
                    {programsWithFlyer.map((p) => (
                      <span key={p.product_id} className="rounded bg-gray-200 px-1.5 py-0.5 text-[0.65rem] text-gray-600">
                        {p.product_id}-flyer.pdf
                      </span>
                    ))}
                  </div>
                </div>

                {/* Signature status */}
                {sigOk ? (
                  <div className="flex items-center justify-between rounded-md border border-emerald-100 bg-emerald-50 px-3 py-2 text-xs text-emerald-700">
                    <div className="flex items-center gap-2">
                      <svg width="12" height="12" viewBox="0 0 16 16" fill="none">
                        <path d="M13.3 4.3L6 11.6 2.7 8.3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                      Your signature + company disclaimer will be attached
                    </div>
                    <button
                      onClick={() => setSigFixOpen(true)}
                      className="rounded border border-emerald-200 bg-white px-2.5 py-1 text-xs font-medium text-emerald-700 hover:bg-emerald-50 transition-colors"
                    >
                      Review
                    </button>
                  </div>
                ) : (
                  <div className="flex items-center justify-between rounded-md border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">
                    <div className="flex items-center gap-2">
                      <svg width="12" height="12" viewBox="0 0 16 16" fill="none">
                        <path d="M8 1a7 7 0 100 14A7 7 0 008 1zM7 4h2v5H7V4zm0 6h2v2H7v-2z" fill="currentColor" />
                      </svg>
                      Email signature required.
                    </div>
                    <button
                      onClick={() => setSigFixOpen(true)}
                      className="rounded bg-red-600 px-2.5 py-1 text-xs font-medium text-white hover:bg-red-700 transition-colors"
                    >
                      Fix
                    </button>
                  </div>
                )}

                {error && (
                  <p className="text-xs text-red-600 bg-red-50 border border-red-200 rounded px-3 py-2">
                    {error}
                  </p>
                )}

                {/* Actions */}
                <div className="flex items-center justify-between pt-1">
                  {tab !== "myself" ? (
                    <FollowUpToggle
                      enabled={followUpEnabled}
                      days={followUpDays}
                      mode={followUpMode}
                      onToggle={setFollowUpEnabled}
                      onDaysChange={setFollowUpDays}
                      onModeChange={setFollowUpMode}
                    />
                  ) : <div />}
                  <div className="flex items-center gap-3">
                    <button
                      onClick={onClose}
                      className="text-xs text-gray-400 hover:text-gray-600"
                    >
                      Cancel
                    </button>
                    <button
                      onClick={handleSend}
                      disabled={sending}
                      className="inline-flex items-center gap-1.5 rounded-md bg-red-600 px-4 py-1.5 text-xs font-medium text-white hover:bg-red-700 disabled:opacity-50"
                    >
                      {sending && <LoadingSpinner size="sm" />}
                      {sending ? sendProgress || "Sending..." : "Send Email"}
                    </button>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
      </div>
    {sigFixOpen && (
        <SignatureFixModal
          onClose={() => setSigFixOpen(false)}
          onSaved={() => { setSigOk(true); setSigFixOpen(false); setError(null); }}
        />
      )}
    </div>
  );
}
